#!/usr/bin/env bash

#############################################
# LOG INTO THE NGINX CONTAINER VIA SSH  #
#############################################

FIGLET="figlet -w 150 -f cybermedium"

TEXT="Entering Shell..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi

# ssh -o PasswordAuthentication=no    \
#     -o StrictHostKeyChecking=no     \
#     -o UserKnownHostsFile=/dev/null \
#     -p 2222                         \
#     -i workspace/insecure_id_rsa    \
#     root@localhost

cd laradock
docker-compose exec nginx bash

TEXT="Done. Exiting Shell.." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi


