#!/usr/bin/env bash

########################################
# CLEANUP OF TEMPORARY FILES AND CACHE #
########################################

clear 

FIGLET="figlet -w 150 -f cybermedium"

TEXT="Deleting Temporary Views..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
rm -rf ./storage/framework/views/*
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Deleting Temporary Sessions..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
rm -rf ./storage/framework/sessions/*
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Deleting Temporary Logs..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
# rm -rf ./storage/logs/*
echo '' > ./storage/logs/laravel.log
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Deleting Uploaded Files..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
rm -rf ./public/files/*
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Deleting .DS_Store files..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
find . -name ".DS_Store" -delete
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Clearing Routes Cache..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
php artisan route:clear
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Clearing Config Cache..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
php artisan config:clear
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Clearing Views Cache..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
php artisan view:clear
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Clearing General Cache..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
php artisan cache:clear
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Clearing DebugBar Storage..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
php artisan debugbar:clear
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

TEXT="Finished Clearing Caches..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi
