#!/usr/bin/env bash

########################################
# ARCHIVE OF CURRENT PROJECT           #
########################################

FIGLET="figlet -w 150 -f cybermedium"
TIMESTAMP=$(date +%Y%m%d_%H%M)
TGZ="./anima_$TIMESTAMP.tgz"

cd ..

TEXT="Archiving Project Files..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
tar zcf $TGZ ./anima
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

