#!/usr/bin/env bash

########################################
# ARCHIVE OF CURRENT PROJECT           #
########################################

FIGLET="figlet -w 150 -f cybermedium"
cd ..

TEXT="Syncing Project Files to local GitHub repo..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
rsync -a /Users/epi/Sites/anima/anima/public/ /Users/epi/Documents/GitHub/ralphreijs.github.io/anima
TEXT="Done." && if type figlet &> /dev/null; then figlet $TEXT; else echo $TEXT; fi

