#!/usr/bin/env bash

#############################################
# BRING DOCKER DOWN AND REMOVE CONTAINERS   #
#############################################

FIGLET="figlet -w 150 -f cybermedium"

cd laradock
TEXT="Shutting down and removing all Docker containers..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
docker stop $(docker ps -a -q)
docker-compose down -v --rmi all --remove-orphans
docker rm $(docker ps -a -q)
TEXT="Done." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi

TEXT="Cleaning up remains..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
docker rm -f $(docker ps -a -q)
docker system prune -a -f
docker rmi $(docker images -a -q)
TEXT="Done." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi

TEXT="Cleaning up unused Docker Volumes..." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi
docker volume prune -f 
docker volume rm $(docker volume ls -q)
TEXT="Done." && if type figlet &> /dev/null; then $FIGLET $TEXT; else echo $TEXT; fi | if type lolcat &> /dev/null; then lolcat; fi

cd ..
./anima_cleanup


